[package]
name = "registry-storage"
version.workspace = true
edition.workspace = true
license = "AGPL-3.0-only"

[dependencies]
anyhow.workspace = true
registry-protocol.workspace = true
postgres.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3.14"
