[package]
name = "registry-crypto"
version.workspace = true
edition.workspace = true
license = "AGPL-3.0-only"

[dependencies]
anyhow.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
rand.workspace = true
registry-protocol.workspace = true
watt-did.workspace = true
